language: go

go:
    - 1.12.x

matrix:
    include:
        - os: linux
        - os: windows
        - os: osx
          osx_image: xcode11

install:
    - go get -t -v ./...
    - go install ./cmd/devd

script:
    - go test -v -race ./...

notifications:
    email:
        - aldo@corte.si
